"use client";
import { useTheme } from "next-themes";
import { MagicCard } from "@/components/magicui/magic-card";
import Image from "next/image";
import paradox from "../../public/paradox.png";
import mist from "../../public/mist.png";
import ecos from "../../public/ecos.png";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export default function Books() {
  const { theme } = useTheme();
  return (
    <>
      <div className="mx-4 md:mx-36 my-20 md:my-20">
        <h1 className="text-center text-3xl md:text-4xl text-[#6366F1] font-semibold mb-4">
          Sample Books Generated by BookAI
        </h1>
        <p className="text-center text-lg md:text-xl mb-10">
          Explore some of the captivating books created using our AI technology.
        </p>
        <div
          className={
            "flex h-[full] w-full flex-col gap-6 lg:h-[600px] lg:flex-row "
          }
        >
          <MagicCard
            className="cursor-pointer shadow-2xl"
            gradientColor={theme === "dark" ? "#262626" : "#e9ecef"}
          >
            <div className="flex flex-col items-center gap-4 p-6 text-center">
              <Image
                src={paradox}
                alt="paradox"
                width={190}
                height={250}
                className="rounded"
              />
              <h2 className="text-3xl">Science Fiction</h2>
              <p className="text-lg text-gray-600 dark:text-gray-300">
                "As Dr. Elara stepped through the shimmering portal, she knew
                there was no turning back. The fate of two universes now rested
                in her hands..."
              </p>
              <Button
                className={cn(
                  "md:w-[188px] md:h-[52px] dark:text-white rounded-md text-xl bg-[#8a2be2] font-medium hover:bg-[#FE6100]"
                )}
                style={{
                  backgroundImage: "linear-gradient(45deg, #726bff, #57b6fe)",
                }}
              >
                Read more
              </Button>
            </div>
          </MagicCard>

          <MagicCard
            className="cursor-pointer shadow-2xl"
            gradientColor={theme === "dark" ? "#262626" : "#e9ecef"}
          >
            <div className="flex flex-col items-center gap-4 p-6 text-center">
              <Image
                src={mist}
                alt="paradox"
                width={190}
                height={250}
                className="rounded"
              />
              <h2 className="text-3xl">Mystery</h2>
              <p className="text-lg text-gray-600 dark:text-gray-300">
                "The old lighthouse stood silent, its beacon long extinguished.
                But on foggy nights, some swore they could still see its ghostly
                light..."
              </p>
              <Button
                className={cn(
                  "md:w-[188px] md:h-[52px] dark:text-white rounded-md text-xl bg-[#8a2be2] font-medium hover:bg-[#FE6100]"
                )}
                style={{
                  backgroundImage: "linear-gradient(45deg, #726bff, #57b6fe)",
                }}
              >
                Read more
              </Button>
            </div>
          </MagicCard>

          <MagicCard
            className="cursor-pointer shadow-2xl"
            gradientColor={theme === "dark" ? "#262626" : "#e9ecef"}
          >
            <div className="flex flex-col items-center gap-4 p-6 text-center">
              <Image
                src={ecos}
                alt="paradox"
                width={190}
                height={250}
                className="rounded"
              />
              <h2 className="text-3xl">Fantasy</h2>
              <p className="text-lg text-gray-600 dark:text-gray-300">
                "The ancient prophecy spoke of a child born with starlight in
                their eyes. As the comet blazed overhead, the kingdom held its
                breath..."
              </p>
              <Button
                className={cn(
                  "md:w-[188px] md:h-[52px] dark:text-white rounded-md text-xl bg-[#8a2be2] font-medium hover:bg-[#FE6100]"
                )}
                style={{
                  backgroundImage: "linear-gradient(45deg, #726bff, #57b6fe)",
                }}
              >
                Read more
              </Button>
            </div>
          </MagicCard>
        </div>
      </div>
    </>
  );
}
